version: "3.9"

services:
  backend-app:
    build: ./backend
    container_name: backend-app
    environment:
      ASPNETCORE_URLS: "http://+:80"
      ASPNETCORE_ENVIRONMENT: "Staging"
    depends_on:
      - database

  frontend-app:
    build ./frontend

  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"  # TODO: задавать через переменные окружения
      POSTGRES_PASSWORD: "password"  # TODO: задавать через переменные окружения
    volumes:
      - ./.pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:1.19.10
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - okr-backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf